<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationTitle>Async &amp; Multithreaded Processing Hub</ApplicationTitle>
    <RootNamespace>Lab07_AsyncThreads</RootNamespace>
    <AssemblyName>Lab07_AsyncThreads</AssemblyName>
  </PropertyGroup>

</Project>
